galaxy_info:
  author: Leigh MacDonald
  description: Setup TF2
  # company: your company (optional)

  issue_tracker_url: https://github.com/leighmacdonald/uncletopia/issues

  license: MIT

  min_ansible_version: 2.9

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  platforms:
  - name: Ubuntu
    versions:
    - 20.04

  galaxy_tags:
    - "tf2"
    - "teamfortress2"

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
