---

- name: Create minio_data volume
  docker_volume:
    name: minio_data
    state: present

- name: Create minio_data container
  docker_container:
    name: minio
    image: minio/minio
    restart: true
    pull: true
    purge_networks: true
    restart_policy: unless-stopped
    recreate: true
    env:
      MINIO_ROOT_USER: {{ minio.user | default(mimir) }}
      MINIO_ROOT_PASSWORD: {{ minio.password | default(mimir) }}
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    networks:
      - name: caddy_net
    volumes:
      - minio-data:/data
    ports:
      - 127.0.0.1:9000:9000
